Link property
richardhsu/jquery.ambiance pull request #5
Opened 2018-10-17 09:07 UTC by josejavierfm

Link with linkname and linkblank properties asociated

2018-10-17 22:08 UTC, richardhsu requested changes
Thanks for contributing, again this project isn't really in any active development but this addition looks good, please review my comments and update the PR and we can get it merged, thanks!

2018-10-18 06:03 UTC, josejavierfm commented
i see the file weel indent on my IDE now

2018-10-18 18:13 UTC, richardhsu approved these changes

2018-10-18 18:15 UTC, merged

2018-10-18 18:15 UTC, richardhsu commented
@josejavierfm Thank you, merged!